# Generated by Django 3.2 on 2021-11-27 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
