# Generated by Django 3.2 on 2021-11-29 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20211128_0120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='published_date',
        ),
    ]
