# Generated by Django 3.2 on 2021-12-06 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_alter_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='author',
        ),
    ]
